### ISSUE TITLE
Hotkeys / keyboard shortcuts support

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Amplicode/amplicode-frontend#1]
Provide means for the framework users to configure hotkeys / keyboard shortcuts. Use declarative approach. Use existing solution if possible.

Out-of-the-box the following hotkeys should be available:

- Switching between tabs
- Standard actions in entity list components:
  - creating entity instance
  - editing entity
  - removing entity
- Applying changes in editor

It should be possible for the framework users to redefine the hotkeys for above listed actions and define their own custom hotkeys for arbitrary actions.

#### Hotkeys library

Hotkeys implementation is based on [hotkeys.js](https://github.com/jaywcjlove/hotkeys)

#### Exist 2 types of hotkeys:

- Global - available anywhere in an application;
- Local - available for correct open screen;

Register global hotkeys outside Screen with `useHotkey()` hook.
Register local hotkeys inside the Screen with `useScreenHotkey()` hook.

```typescript
const alertAboutPressingNHotkeyConfig: HotkeyConfig = {
  pattern: 'n',
  description: 'Alert about pressing n',
  categoryName: 'Any category name',
};
const alertAboutPrassingN = useCallback(() => alert("N was pressed!"), []);
// Outside screen
useHotkey(alertAboutPressingNHotkeyConfig, alertAboutPrassingN);
// Inside screen
useScreenHotkey(alertAboutPressingNHotkeyConfig, alertAboutPrassingN);
```

#### Registration hotkey
When you use `useHotkey()` or  `useScreenHotkey()` hooks the hotkey will be registered on component mounting and unregistered on component unmounting.

#### HotkeyConfig
An object which configures hotkey.
```typescript
interface HotkeyConfig {
    hotkey: string; // pattern for defining keyboard hotkeys. Patterns work like in hotkeys-js library
    description: string; // unique using like id of hotkey
    categoryName: string;
}
```

#### HotkeyStore

Exist 3 types of hotkeyConfigs:
- defaultHotkeyConfigs - initialized with creating store;
- dynamicHotkeyConfigs - currently registered hotkeyConfigs in runtime;
- hotkeyConfigs - merged version of defaultHotkeyConfigs and dynamicHotkeyConfigs;

#### HotkeyInfo component

Render information about hotkeys from hotkeyConfigs.

#### Using defaultHotkeyConfigs

When you use `useScreenHotkey(hotkeyConfig, hotkeyCallback)` hook. This hotkey will be available just for a current screen. If you want to see info about this hotkey inside HotkeyInfo component independently on the current screen. You need to add the hotkeyConfig object to defaultHotkeyConfigs.

### Default amplicode hotkeys

`@amplicode/codegen` adds some default application hotkeys while generation:
- useDefaultScreenHotkeys()
- useDefaultEditorHotkeys()
- useDefaultBrowserHotkeys()

### QA Notes

Button for open list of available hotkeys is placed in the header:
![7375ff06ba14ba5e77374cc8610756b7](https://user-images.githubusercontent.com/34520941/141777049-5fd6f31d-3603-4ce4-ad5c-89a09255687a.png)

The list of available hotkeys looks like this:

![7816e24481c4ac300ab45b15146f2f50](https://user-images.githubusercontent.com/34520941/141777548-b6522af7-a9bb-4f85-9962-30734f1da013.png)

**Comment by owlet1997** [comment]
please remove the hotkey for filter from help list and stub: 
![image](https://user-images.githubusercontent.com/45730069/142429365-5a3c7ed3-5c23-45d2-a59e-a43b5f0025e9.png)
