### ISSUE TITLE
Error in the EmailTemplateCreate screen.

### ISSUE THREAD

**Issue by MaslovMaximV** [Amplicode/amplicode-frontend#1002]
**IDEA version**: IntelliJ IDEA 2023.1.5 (Ultimate Edition)
**OS**: macOS 13.3.1
**Plugin version**:
    org.jetbrains.kotlin (231-1.9.0-release-358-IJ8770.65)
    com.intellij.lang.jsgraphql (4.0.1)
    com.haulmont.amplicode (0.1.SNAPSHOT3133-231)
**Project**: [amplicode-email-template.zip](https://github.com/Amplicode/amplicode-frontend/files/12299418/amplicode-email-template.zip)
**Steps**: 
1. Create an Amplicode project
2. Create an React UI module
3. Install email add-on
4. Start back and front
5. Open Email Template > Create

**AR**: An error occurs
<img width="1779" alt="Screenshot 2023-08-07 at 16 22 10" src="https://github.com/Amplicode/amplicode-frontend/assets/126795807/4a92b556-1d87-4076-becf-ddf33cdba3b2">

**Comment by m-orlova** [comment]
@MaslovMaximV Please move this ticket to YT (project - Amplicode Backend).
