### ISSUE TITLE
Error when refreshing page with editor in "new entity" state

### ISSUE THREAD

**Issue by alexbudarov** [Amplicode/amplicode-frontend#102]
Reproduced on https://github.com/Amplicode/amplicode-mvp-petclinic
- Open Pet List
- Press Create button
- Press Refresh in the browser

Error happens:
![image](https://user-images.githubusercontent.com/6158807/144448895-1be79a17-7ad1-4c30-a083-02b6e47ad688.png)

**Comment by vyacheslav-pushkin** [comment]
@ilya-trifonov The commit fixing this ticket was merged into `development` instead of `master`. Please create a PR to for `master`.

**Comment by owlet1997** [comment]
frontend generator version 0.12.0
mvp-petclinic project is used 

**TC:**
1. Generate entity-management component for any entity
2. Run an app -> Login
3. Open the entity browser -> Create
4. Refresh the page

**AR:**
the same error occurs:
![image](https://user-images.githubusercontent.com/45730069/159495871-db10ca5a-da9e-49a2-9a44-ffcbab55fa61.png)
