### ISSUE TITLE
Security restrictions for UI elements

### ISSUE THREAD

**Issue by vadimbasko** [Amplicode/amplicode-frontend#1061]

**Comment by vadimbasko** [comment]
<https://github.com/marmelab/ra-auth-acl>
<https://marmelab.com/react-admin/AuthRBAC.html>

**Comment by vadimbasko** [comment]
- add delete permisson

**Comment by MaslovMaximV** [comment]
I have defined roles for the users, but in my case the USER user has access to the screens, but no access to some components. As a result, I can't see the whole screen.

Generator: 0.62.2
IntelliJ IDEA 2023.3.2 (Ultimate Edition)
macOS 14.1.1
Plugins:
  com.intellij.lang.jsgraphql (233.13135.65)
  com.haulmont.amplicode (0.1.SNAPSHOT3717-233)

Prerequisites:
1. Open petclinic project

Steps: 
1. Open ACL file
2. Add code
```typescript
export const ACL: AclType = {
  ROLE_ADMIN:{
    OwnerDTO:{
      enabled: true,
      list: true,
      create: false,
      edit: true,
      show: true,
      delete: true,
    },
    PetDTO:{
      enabled: true,
      list: true,
      create: false,
      edit: true,
      show: true,
      delete: true,
    }
  },
  ROLE_USER:{
    OwnerDTO:{
      enabled: true,
      list: true,
      create: false,
      edit: false,
      show: true,
      delete: false,
    },
    PetDTO:{
      enabled: true,
      list: true,
      create: false,
      edit: false,
      show: true,
      delete: false,
    }
  }
};
```
3. Start backend and frontend
4. Log in as user
AR: I can't see the pets and owners screens.
ER: I can see the owners and pets screens, but can't edit, create or delete.

![Image](https://github.com/Amplicode/amplicode-frontend/assets/126795807/de44d7da-91ee-4e77-a356-2d803ce34212)
