### ISSUE TITLE
The component opening a screen from the add-on breaks add-on localization

### ISSUE THREAD

**Issue by m-orlova** [Amplicode/amplicode-frontend#110]
Project example: [localization.zip](https://github.com/Amplicode/amplicode-frontend/files/7728382/localization.zip)

There is the `ShowPersistentParameters.tsx` component that represents the button by clicking on which a screen from the [Persistent Parameters add-on](https://github.com/Amplicode/amplicode-persistentparameters/tree/main/frontend) is opened.

This component is added to the `Home.tsx` screen and the localization for the Persistent Parameters add-on is broken. If remove `ShowPersistentParameters.tsx` from the home screen, localization for the add-on works.

**Comment by vyacheslav-pushkin** [comment]
@m-orlova For now this can be solved by moving `import "./i18n/i18nInit";` to the top of `index.tsx`. Later we will rework the mechanism of sharing i18n with addons so that it doesn't depend on import order (will be a breaking change).
