### ISSUE TITLE
Login screen doesn't react well on "login failed" login result

### ISSUE THREAD

**Issue by alexbudarov** [Amplicode/amplicode-frontend#113]
Open any project, e.g. https://amplicode-addons.demo.haulmont.com/

Logout, and try to login with invalid credentials.

Expected:
Message with "login failed" text or something like that.

Actual:
Screen doesn't react on login result:
![image](https://user-images.githubusercontent.com/6158807/147090354-ffcfd72b-6956-46d7-88f2-3a6112277e48.png)

Probably needs a change on backend side.

**Comment by HegelPro** [comment]
I checked on the actual version [petclinic backend](https://github.com/Amplicode/amplicode-mvp-petclinic). It still works wrong on this backend.

Actual:
After trying to login with invalid credentials the request redirects to another request. 

Expected:
If credentials are wrong the request must send 404 error without redirection. Like in `jmix` application.

**Comment by alexbudarov** [comment]
@andreysubbotin We are waiting for the backend fix on the petclinic master.
