### ISSUE TITLE
Revise generated project structure

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Amplicode/amplicode-frontend#125]
## Problem

Current project structure is inconsistent. We have files related to security in different places, same with Screen API, some of the generated components (such as app header) have their own folders, but app menu for example is on the same level with `App.tsx`, etc.

## Suggested structure

```
src/
├─ app/
│  ├─ header/
│  ├─ main/
│  ├─ menu/
│  │  ├─ Menu.css
│  │  ├─ Menu.tsx
│  ├─ login/
│  ├─ screens/
│  │  ├─ home/   
│  │  ├─ owner/
│  │  ├─ pet/
│  ├─ App.css
│  ├─ App.tsx
│  ├─ App.test.tsx
├─ dev/
├─ gql/
├─ core/
│  ├─ addons/
│  │  ├─ addons.ts
│  ├─ hotkeys
│  │  ├─ hotkey-configs.ts
│  ├─ i18n
│  │  ├─ en.json
│  │  ├─ i18n-init.ts 
│  ├─ screen-api
│  │  ├─ ScreenTabs.tsx
│  │  ├─ screen-registry.ts
│  ├─ security/
│  │  ├─ security.ts
│  │  ├─ security-store.ts
├─ config.ts
├─ index.css
├─ index.tsx
├─ react-app-env.d.ts
├─ reportWebVitals.ts
├─ setupTests.ts
```

**Explanation:**

- **app** folder is for UI components except generated screens. E.g. login screen, header, etc. This is the code that is most likely to be customized.
- **app/screens** folder is for generated screens. Whatever is added when you click "Add frontend component" in Studio.
- **dev** is for palette, previews, etc. - tooling-related stuff.
- **gql** is for generated TS typings.
- **core** is for generated code that we more or less consider part of framework. Addons config, i18n, screen API, security, etc. This code is less likely to be customized by hand. Some of it might be heavily changed by tooling.

**File naming convention**

- If the file contains a React component - use `PascalCase`, i.e. the same case that you use to name the component itself. E.g. `MyComponent.tsx`, `MyComponent.css`.
- If the file contains a single function - use `camelCase`, i.e. the same case that you use to name the function itself. E.g. `myFunction.ts`.
- Use `snake-case` everywhere else. E.g. `some-file.ts`.
- Files generated by Create React App doesn't seem to follow a consistent naming convention. Leave them as they are.

## TO DO

- [x] Modify the project structure according to above.
- [x] Add information from **Suggested structure** above to CONTRIBUTION.md

**Comment by reznikova21** [comment]
@ilya-trifonov please add QA notes

**Comment by vyacheslav-pushkin** [comment]
@reznikova21 I think in this case there is no need for QA Notes, ticket already describes very clearly what was changed.
