### ISSUE TITLE
Implement initialization hook for React Buddy

### ISSUE THREAD

**Issue by web-devel** [Amplicode/amplicode-frontend#145]
See `src/dev/hook.ts`. Implicitly log-in user with some default credentials (e.g. admin/admin)
Pass credentials through config/env variables 

### QA Notes

React Buddy component preview should function without having to manually log in.

**Comment by owlet1997** [comment]
@web-devel @karandashovrz 
the [project](https://github.com/Amplicode/amplicode-mvp-petclinic/tree/graphql-M5) was used
RB plugin 2022.1SNAPSHOT251

**TC:**
1. Open the PetDetails screen
2. Start the preview using React Buddy without starting a server
3. Open the Menu.tsx -> Start the preview

**AR:**
the infinite spinner is displayed in both preview screens:
![image](https://user-images.githubusercontent.com/45730069/155529596-2d4e0113-e366-4a75-bf09-7d304f13eb8e.png)
![image](https://user-images.githubusercontent.com/45730069/155529617-49c734ac-fd49-49e8-8b0d-fe4c0126ee0d.png)
