### ISSUE TITLE
Make screen route to be a separate screen template parameter

### ISSUE THREAD

**Issue by alexbudarov** [Amplicode/amplicode-frontend#178]
"Entity list" and "Entity management" templates create screen with a route (which is then used in the menu and screen registration file).
Currently the route constant is automatically derived from the component class name.

We think that the user should be able to specify the screen route manually in the screen wizard. Let's make it separate screen parameter.
The parameter should have some mark, so that Studio can identify it and provide automatic filling of the default value in the wizard (also basing on the component name).

**Comment by vyacheslav-pushkin** [comment]
> The parameter should have some mark, so that Studio can identify it and provide automatic filling of the default value in the wizard (also basing on the component name).

I think the simplest way is to add a new property type, e.g. `StudioTemplatePropertyType.ROUTE`.
