### ISSUE TITLE
Buggy navigation (refactored crud templates)

### ISSUE THREAD

**Issue by alexbudarov** [Amplicode/amplicode-frontend#195]
Branch: pv/refactor/crud-screens

- Launch frontend
- Open Owner List from menu
- Open any Owner for editing
- Click "Pet List" in menu

Expected: Pet List is opened
Actual: Owner editor under pet list is opened %)

![image](https://user-images.githubusercontent.com/6158807/155673290-0a786228-f70a-46a6-bc1e-5869cb3394c0.png)

**Comment by vyacheslav-pushkin** [comment]
Not reproduced in latest version of CRUD screens
