### ISSUE TITLE
Read only list should not have action buttons 

### ISSUE THREAD

**Issue by vadimbasko** [Amplicode/amplicode-frontend#207]
In example app open [http://localhost:3000/#/read-only-owner-list/](http://localhost:3000/#/read-only-owner-list/)

![read-only-list](https://user-images.githubusercontent.com/5281427/156558562-31477f1d-3417-4969-819e-260e7fc7f425.jpg)

AR:
- 'create' button exist in buttons pane
- 'edit' icon instead of 'view' in list items

ER: 
- no create button should be available
- in list items should be 'view' icon

Also it's better rename 'edit' with 'view' function names in generated code, which open details screen from list.

**Comment by owlet1997** [comment]
unresolved variable REFETCH_QUERIES is used in the generated screens:
**template: cards + view**
![image](https://user-images.githubusercontent.com/45730069/159471326-3def840e-ccae-43a4-8b5e-145be2ac738c.png)

**template: cards + view with details**
![image](https://user-images.githubusercontent.com/45730069/159471362-70169907-9204-41e6-bd7f-dc4c80e4eda6.png)

**Comment by vadimbasko** [comment]
Issue described in comment is fixed as part of #143. Please wait for next codegen version with #143 included.

**Comment by owlet1997** [comment]
Generator version: 0.13.2

template **list + view**:
**AR:**
the Delete button is added to each list item:
![image](https://user-images.githubusercontent.com/45730069/161975338-816df8f1-ac5f-4f48-a33c-193118562f2c.png)
so item could be deleted

**ER:**
list items should not have any buttons

-----------------------
template **list + view with details**:
**AR:**
1. The Delete button is also added to each list item:
![image](https://user-images.githubusercontent.com/45730069/161976051-004999f9-ea23-4171-b243-b0e51eba78c5.png)

Open any item -> Change value of any field -> Submit
**AR:**
changes are saved and displayed in the list
**ER:**
1. The Delete button should not be added to a list item
2. After opening anu instance user should not be able to change anything so probably Submit button should be disabled

**Comment by ilya-trifonov** [comment]
@owlet1997 
Visibility of the delete button doesn`t depend on the selected mod. If you leave the delete mutation empty, this button will not be displayed

**Comment by owlet1997** [comment]
@ilya-trifonov honestly it's hard to recognize without such explanation but ok
