### ISSUE TITLE
npm install fails due to integrity check when using a different registry

### ISSUE THREAD

**Issue by owlet1997** [Amplicode/amplicode-frontend#226]
**Environment:**
IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Build #IU-213.6777.52, built on January 28, 2022
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.14.0-1027-oem
GC: G1 Young Generation, G1 Old Generation
Memory: 1262M
Cores: 8
Non-Bundled Plugins:
    some.awesome (1.14)
    org.intellij.plugins.hcl (0.7.15)
    org.jetbrains.kotlin (213-1.6.10-release-944-IJ6461.79)
    com.intellij.lang.jsgraphql (3.1.0)
    com.haulmont.amplicode (0.1.SNAPSHOT612-213)
    CUBA (15.8-213)
Kotlin: 213-1.6.10-release-944-IJ6461.79
Current Desktop: ubuntu:GNOME
registry: Amplicode registry

**TC:**
1. Clone the [project](https://github.com/Amplicode/amplicode-mvp-petclinic)
2. Remove the existing frontend module
3. Add a new frontend module using custom generator version 0.10.0
4. Open the frontend/package.json file -> Run `npm i`

**AR:**
packages have not been installed:
```
/usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --scripts-prepend-node-path=auto
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EINTEGRITY
npm ERR! sha512-8izbkUrlasVw5oZArTp3/eQhEOJrolUDXs1OIMYRR/XPVp+voz4dSURGqE32bglmqd/K+Ok8oEFDWh5QO1qkBg== integrity checksum failed when using sha512: wanted sha512-8izbkUrlasVw5oZArTp3/eQhEOJrolUDXs1OIMYRR/XPVp+voz4dSURGqE32bglmqd/K+Ok8oEFDWh5QO1qkBg== but got sha512-2s8ble+C8oS3mInvW6C8rZvKZKMgCT7yAFIz8phUBX902QopphQ98sUewYikW+dq74509pfLTAjFV7+DIQMwLg==. (9793 bytes)
npm ERR! code EINTEGRITY
npm ERR! sha512-nK4UoyKKfiTyHLEu3rjdX2vC1ftKbpJYFXJqTKcwL5E2xyrrpQ2QFhPuhQ1DNOmIxIOtEQf8hopv5wFbm3OdSg== integrity checksum failed when using sha512: wanted sha512-nK4UoyKKfiTyHLEu3rjdX2vC1ftKbpJYFXJqTKcwL5E2xyrrpQ2QFhPuhQ1DNOmIxIOtEQf8hopv5wFbm3OdSg== but got sha512-7UsiBBu4+FcBuuswm18S05MRtAQOGIUPcxYKQDOiOELnF9qv6knm1CtCYR8fEkP9/iDw0I2tQmJNrX9m2G0HXw==. (15749 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shatalova/.npm/_logs/2022-03-14T13_51_15_765Z-debug.log
```

After removing the package-lock.json file and repeating the process dependencies are installed correctly

**Comment by vyacheslav-pushkin** [comment]
@HegelPro 

The reason this happens is that:

1. We are using a registry different from the one written in `package-lock` (`registry` field)
2. Hashes (`integrity` field) doesn't match for some reason.

First step is trying to reproduce this using Amplicode registry. If it doesn't reproduce - ask @owlet1997 to provide project. If still doesn't reproduce - project with `node_modules`. If still doesn't reproduce - check if problem disappears if @owlet1997 run `npm cache clean --force`.

Next step is to identify the problematic packages (can be done by searching the `package-lock` for the hashes mentioned in the error message).

Also please check whether the problem disappears if you remove all `registry` and `integrity` entries from `package-lock`.

Let's me know after this is done and I might provide more insight.

**Comment by HegelPro** [comment]
The problem wasn't depend of Amplicode registry.
The problem was because we had only `integrity` field without `resolved` field with refer to registry in package-lock from `app` template.
We need to add `resolved` and `integrity` fields to package-lock. Or we need to remove both of them.

I prefer this algorithm for updating package-lock:
0) Set up default npm registry
1) Remove old `example-app`
2) Generate `app` template(without changing dependnces to locale tarballs)
3) Maybe need to remove old package-lock
4) Install npm packages and run application
5) If application works correctly, without throwing errors overwrite package-lock to new generated.
6) Change value of `name` field in the new package-lock to placeholder for `appShortName` varaible ("<%= appShortName %>")

**Comment by vyacheslav-pushkin** [comment]
@HegelPro Please check whether package-lock contains integrity hashes from the locally built libraries. If yes - this needs to be fixed (see [this comment](https://github.com/cuba-platform/frontend/issues/474#issuecomment-1080361518)).

**Comment by HegelPro** [comment]
In [amplicode-frontend](https://github.com/Amplicode/amplicode-frontend) `integrity` and `resolved` have already been taken from npm regestry.
