### ISSUE TITLE
Automatic relogin on session

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Amplicode/amplicode-frontend#228]
Implement automatic relogin if user session is still active (similar to how it works in Jmix).

When application is started, make a request to `userInfo` endpoint (see [userInfo backend documentation](https://youtrack.haulmont.com/articles/PLAT-A-688/User-Info)). If the request is not authorized, consider the user logged out and redirect them to login screen. Otherwise consider them logged in.

If the user is logged in, they should stay logged in:
- if the page is reloaded
- if browser is closed and reopened
- if the application is opened in another tab

**Comment by vyacheslav-pushkin** [comment]
@andreysubbotin please add docs link to the ticket description once the docs are available. Thanks.

**Comment by andreysubbotin** [comment]
Documentation: https://youtrack.haulmont.com/articles/PLAT-A-688/User-Info
