### ISSUE TITLE
Incorrect menu item is created if `Add to menu` checkbox was activated in template `Entity details`

### ISSUE THREAD

**Issue by owlet1997** [Amplicode/amplicode-frontend#262]
generator version 0.12.0
mvp-petclinic project was used

**TC:**
1. New -> Frontend component
2. Choose Entity details template -> Fill all fields correctly
3. Activate the checkbox `Add to menu` if deactivated -> Finish
4. Open the Menu.tsx file

**AR:**
all fileds of added menu item are filled with `undefined`: 
![image](https://user-images.githubusercontent.com/45730069/159473793-1d8e9b4a-8c56-4128-a51d-8f161f299257.png)

**ER:**
to be discussed
- should it be possible to add the entity details screen to a menu?

**Comment by ilya-trifonov** [comment]
Already fixed
