### ISSUE TITLE
env.production file should not be gitignored

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Amplicode/amplicode-frontend#318]
Change`.env.production.local` to `.env.production`.

Update petclinic frontend once done.

### QA Notes

Check that generated app has `.env.production` file and that it can be committed.

**Comment by TikhomirovME** [comment]
when creating frontend module `.env.production.local` is present in the file list
![изображение](https://user-images.githubusercontent.com/83810852/163542879-1f33041d-c3bf-4e86-bee9-384f72b0d45a.png)
The created frontend module contains .`env.production` and `.env.production.local` .
The `.env.production.local` is specified in .gitignore
![изображение](https://user-images.githubusercontent.com/83810852/163543023-118a3023-e480-422d-9dcd-baa9ed34d727.png)
