### ISSUE TITLE
Bundled schema is not updated when adding a screen

### ISSUE THREAD

**Issue by alexbudarov** [Amplicode/amplicode-frontend#329]
Generator version: 0.17.0
Project: attached
[books.zip](https://github.com/Amplicode/amplicode-frontend/files/8504504/books.zip)

Entity:
```
input GenreInput {
  allowedForChildren: Boolean!
  id: ID
  title: String
}
```

Open frontend.
Menu -> Genres -> New -> fill any fields -> Submit.
Exception happens in console:
```
react_devtools_backend.js:3973 TypeError: Cannot use 'in' operator to search for 'getFields' in undefined
    at getTypeFields (getTypeFields.ts:6:9)
    at getFieldTypeName (transform.ts:102:30)
    at transform.ts:61:27
    at Array.forEach (<anonymous>)
    at transform (transform.ts:54:31)
    at serializeCustomScalars (serializeCustomScalars.ts:20:5)
    at useSubmitEditor.ts:99:12
    at onFinish (Form.js:74:9)
    at useForm.js:846:11
```

![image](https://user-images.githubusercontent.com/6158807/163778893-9d46c577-51d1-4c4b-b0be-b6b072e411af.png)

**Comment by alexbudarov** [comment]
After quick investigation, Genre and GenreInput types for some reason aren't coming to the typeDefs.ts file.

**Comment by alexbudarov** [comment]
![image](https://user-images.githubusercontent.com/6158807/163784579-2994a550-bf8d-483b-b675-7b2d6b4e6b8c.png)

**Comment by vyacheslav-pushkin** [comment]
@vadimbasko merge to `master` and `demo_22_4`
