### ISSUE TITLE
When creating a frontend component in the default directory, in the import { deserialize Custom Scalars } is failing.

### ISSUE THREAD

**Issue by TikhomirovME** [Amplicode/amplicode-frontend#345]
**Playback Steps:**
Create a frontend component  in the default directory.
Open list.tsx or details.tsx

**ER**
All imports are correct

**AR**
 The import { deserialize Custom Scalars } is failing
 
![изображение](https://user-images.githubusercontent.com/83810852/165466619-54c65de7-6c16-472a-9c73-30945ba02991.png)

**ps**
if you specify the folder created in the screens directory, then all imports will be correct

**Environment:**
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2020M
Cores: 8
Non-Bundled Plugins:
    org.intellij.plugins.hcl (221.5080.126)
    com.intellij.lang.jsgraphql (3.1.3)
    com.haulmont.amplicode (0.1.SNAPSHOT884-221)

Kotlin: 221-1.6.20-release-285-IJ5080.210

**Comment by vyacheslav-pushkin** [comment]
`dirShift` seems to be not used in the import
