### ISSUE TITLE
When an entity list tab is opened, GraphQL request is sent twice

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Amplicode/amplicode-frontend#36]

**Comment by vadimbasko** [comment]
Now we are using `useQuery` hook with 'cache-and-network' policy. 

Issue not reproduced for 'network-only' policy.
```
  const { loading, error, data } = useQuery(OWNER_LIST, {fetchPolicy: 'network-only'});
```

As we decide to use 'network-only' by default in #37, issue will be fixed after implementing #37.
