### ISSUE TITLE
Use network-only cache policy by default

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Amplicode/amplicode-frontend#37]
Currently we use the following fetch policy:

```
    query: {
      fetchPolicy: "network-only"
    },
    watchQuery: {
      fetchPolicy: "cache-and-network"
    }
```

We should use `network-only` (i.e. queries will always be execute regardless of whether they are already cached, the result will be saved to cache) for both as this will greatly simplify the default code we generate (remove the code responsible for cache update) and allow us e.g. to remove `listQueryName` answer from `entity-details` generator.

### QA Notes

Check that CRUD screens function without errors (e.g. list is successfully updated when entity is created/edited/deleted).

Studio should not ask for `List query name` anymore when using `entity-management` generator.

**Comment by owlet1997** [comment]
waiting for Studio [ticket](https://youtrack.haulmont.com/issue/AST-72) implementation
