### ISSUE TITLE
Bean validation in entity editor

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Amplicode/amplicode-frontend#373]
When editor screen is submitted, and backend returns an error, show error messages in the editor form.

See [Backend docs](https://youtrack.haulmont.com/articles/PLAT-A-745/Bean-Validation-errors) for  information on response structure. `message` contains localized error message, `path` contains information about which form field is affected.

Error is a bean validation error if `classification` is `BeanValidationError`. 

There are 2 kinds of bean validation errors:

| Kind of bean validation error      | Criteria | UI (**see UI/UX section below!**) |
| ----------- | ----------- | ----------- |
| Field error     | `path` conforms to an existing field in the form | Highlight field, show error message  near the field ![image](https://user-images.githubusercontent.com/8298981/167174819-98a4ddfa-2a95-4eb1-ba82-b80834634185.png) |
| Global error   | `path` is empty or does not conform to an existing field in the form | Show error message in a box below the form ![image](https://user-images.githubusercontent.com/8298981/166940843-6467c618-4bc8-4c71-bd75-35ad1fecbf8e.png) |

### QA Notes:
Bean validation messages will be shown in `PetEditor` screen, when submitting form with values
Identification Number: `@#$@#$@`
Birth Date: `2011-11-11`

**Comment by vyacheslav-pushkin** [comment]
@andreysubbotin please add information about which endpoints in petclinic can be used to trigger bean validation error. We should be able to trigger multiple field errors at once and an error not related to fields (e.g. cross-validation).

**Comment by andreysubbotin** [comment]
@m-orlova please add information about endpoints: https://github.com/Amplicode/amplicode-frontend/issues/373#issuecomment-1119801230

**Comment by m-orlova** [comment]
@vyacheslav-pushkin Bean validation can be triggered in two cases:

1. DTO validation: invoke the `updatePetType` mutation and specify a value for the `name `field containing not only letters.
Example of GQL request body with invalid values:
```
{
  "input": {
    "name": "123"
  }
}
```
Example of GQL request body with valid values:
```
{
  "input": {
    "name": "Cat"
  }
}
```
2. Entity validation before saving: invoke the `updatePet` mutation and specify a blank value for the `identificationNumber` field. Example of GQL request body with invalid values:
```
{
  "input": {
    "identificationNumber": "  "
  }
}
``` 
Example of GQL request body with valid values:
```
{
  "input": {
    "identificationNumber": "123"
  }
}
```
