### ISSUE TITLE
Breadcrumbs show а wrong path

### ISSUE THREAD

**Issue by HegelPro** [Amplicode/amplicode-frontend#39]
If switch between breadcrumbs, breadcrumbs start show a wrong path.

1) Open List -> Open Editor -> Click List Breadcrumbs -> Click Editor Breadcrumbs
Breadcrumbs will duplicate Editor Breadcrumbs.

2) Select `Owner List` and `Pet List` menu lists -> Open editor in one of them.
The editor will be open in breadcrumbs of both tabs.

**Comment by vyacheslav-pushkin** [comment]
duplicate of #101
