### ISSUE TITLE
Error when creating a frontend module in amplicode

### ISSUE THREAD

**Issue by TikhomirovME** [Amplicode/amplicode-frontend#407]
Environment
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2020M
Cores: 8
Non-Bundled Plugins:
    org.intellij.plugins.hcl (221.5080.126)
    com.intellij.lang.jsgraphql (3.1.3)
    com.haulmont.amplicode (0.1.SNAPSHOT1023-221)

Kotlin: 221-1.6.20-release-285-IJ5080.210

Steps:
Install amplicode.
Open petclinic project
Delete the old frontend module.
Create a new frontend module using the 0.18.0 generator. (toolbar amplicode →All New Actions→Frontend module) 

Expected result
The frontend module was created without errors

Actual result
![tempsnip](https://user-images.githubusercontent.com/83810852/169967544-537d2d6c-fa0d-4df1-bc5b-993c6ac29294.png)

https://youtrack.haulmont.com/issue/AST-282

**Comment by vyacheslav-pushkin** [comment]
Putting this on hold for now, should be investigated by Studio team first (works on 0.1.SNAPSHOT995-221 but not on 0.1.SNAPSHOT1023-221). If this is caused by failing generator command we need to see the exact command from the Studio logs.
