### ISSUE TITLE
LookupField / Lookup screen reference doesn't compile

### ISSUE THREAD

**Issue by alexbudarov** [Amplicode/amplicode-frontend#413]
Generator version: 0.18.0

Project: attached
see AuthorLookup.tsx and BookDetails.tsx

```
        <EntityLookupField
            getDisplayName={getAuthorDisplayName}
            label="Author"
            lookupComponent={AuthorLookup}
        />
```

Error message:
> TS2739: Type '(props: AuthorLookupProps) => Element' is missing the following properties from type 'ReactElement<any, any>': type, props, key

**Comment by vyacheslav-pushkin** [comment]
Yes, we switched to using element, so that we can pass props to lookup component. 

The misleading comment is now fixed:

```
// lookupComponent={<YourEntityLookupComponentName/>}
```
