### ISSUE TITLE
App crashes when opening datepicker

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Amplicode/amplicode-frontend#416]
App crashes when opening datepicker if Russian locale is selected.

**Comment by HegelPro** [comment]
I think the problem is that [ru dayjs locale](https://github.com/iamkun/dayjs/blob/dev/src/locale/ru.js) does not match with [the dayjs locale type](https://github.com/iamkun/dayjs/blob/dev/types/locale/types.d.ts)

For example, `fr` dayjs locale works well.
