### ISSUE TITLE
Lookup is not displayed

### ISSUE THREAD

**Issue by TikhomirovME** [Amplicode/amplicode-frontend#468]
Steps
1) Create project
-  Create project with project wizard
-  Show preconfigured starter in pom.xml
- ·Change database type to PostgreSQL
-  Use Data Sources -> dataSource item in the Amplicode tool window
- ·Create empty PostgreSQL database (with PgAdmin or from command line)

2) Data model
· Create entities

3) Backend stuff
· Generate Liquibase scripts (+ -> Diff Changelog)
· Create Spring Data repositories (standard)
· Create Spring GraphQL controllers (standard)
· Generate and show GraphQL schema file 

4)  Create frontend module

-  run npm install
-  launch "npm run generate:watch" in terminal 

 
 5) Create screens (including those using Lookup)
Create a Lookup Screen
Add Lookup to details

6)Run project
Run Frontend

7)Log in to http://localhost:3000/
Perform CRUD operations

ER
When you select the lookup field, a list of created instances of the entity is displayed

Ar
lookUp is not displayed
![изображение](https://user-images.githubusercontent.com/83810852/174249545-2af494ed-ea27-4f68-869f-db02b8a17bf1.png)
![изображение](https://user-images.githubusercontent.com/83810852/174249622-d59ffc29-e8c8-4519-a222-69cd1f063139.png)
![изображение](https://user-images.githubusercontent.com/83810852/174249797-e2fd8155-53bb-4995-9345-b17fc893a1a5.png)
![изображение](https://user-images.githubusercontent.com/83810852/174249870-ec14842f-755d-4fe5-9f85-9cbfab70c9a2.png)

[untitled2.zip](https://github.com/Amplicode/amplicode-frontend/files/8925512/untitled2.zip)

**Comment by ilya-trifonov** [comment]
@TikhomirovME 
You need to use a self-closing tag for the lookup component.
correct example: `lookupComponent={<Lookup />}`
wrong: `lookupComponent={Lookup}`
