### ISSUE TITLE
Error  generating shema.graphql

### ISSUE THREAD

**Issue by TikhomirovME** [Amplicode/amplicode-frontend#551]
Steps:
Create Frontend module.
Open frontend/src/core/schema/schema.graphql

AR
![изображение](https://user-images.githubusercontent.com/83810852/181780303-86c53847-041f-4d19-9e86-40a112026bd9.png)

ER
![изображение](https://user-images.githubusercontent.com/83810852/181780535-b6d1dbd1-853f-404a-8fd2-a84ecb8f0dcc.png)
[untitled11.zip](https://github.com/Amplicode/amplicode-frontend/files/9220740/untitled11.zip)

**Comment by alexbudarov** [comment]
Workaround: manually fix the file every time after new screen creation.
