### ISSUE TITLE
Horizontal menu does not appear in header

### ISSUE THREAD

**Issue by alexbudarov** [Amplicode/amplicode-frontend#583]
Generator version: 0.30.3
Sample project: 
[planes.zip](https://github.com/Amplicode/amplicode-frontend/files/9488379/planes.zip)

The menu component isn't included anywhere in the layout.

![image](https://user-images.githubusercontent.com/6158807/188415048-e6b254fa-a510-4257-9bba-a9e55a15a4fe.png)

**Comment by vadimbasko** [comment]
fixed as part of #403
