### ISSUE TITLE
Add possibility to customize login/logout endpoints

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Amplicode/amplicode-frontend#72]
#### Before tests
1. [Setup database](https://github.com/Amplicode/amplicode-frontend/blob/master/CONTRIBUTING.md#Database)
2. [Run backend](https://github.com/Amplicode/amplicode-frontend/blob/master/CONTRIBUTING.md#Backend)
3. Change directory to `amplicode-frontend/example-app` 
4. Install or update dependencies
```
npm i
```

#### Test login/logout environment variables in development mode
1. Change directory to `amplicode-frontend/example-app`
2. Change login and logout variables in file `.env.development.local` to:
```
REACT_APP_LOGIN_URI=/dev-login-endpoint
REACT_APP_LOGOUT_URI=/dev-logout-endpoint
```
3. Start example-app application in development mode
```
npm start
```
4. Open `http://localhost:3000` in browser with developer conosle in order to see network requests  
5. Try to logout 
6. `POST http://localhost:3000/dev-logout-endpoint` should be called
7. Try to login
8. `POST http://localhost:3000/dev-login-endpoint` should be called

#### Test login/logout environment variables in production mode
1. Change directory to `amplicode-frontend/example-app`
2. Change `PUBLIC_URL` variable in file `.env.production.local` to:
```
PUBLIC_URL=/
```
3. Change login and logout variables in file `.env.production.local` to:
```
REACT_APP_LOGIN_URI=/prod-login-endpoint
REACT_APP_LOGOUT_URI=/prod-logout-endpoint
```
3. Build application
```
npm run build
```
4. Host build locally
```
npx serve -s build
```
5. Open `http://localhost:3000` in browser with developer conosle in order to see network requests  
6. Try to logout 
7. `POST http://localhost:3000/prod-logout-endpoint` should be called
8. Try to login
9. `POST http://localhost:3000/prod-login-endpoint` should be called

**Comment by lovtsovaik** [comment]
@deanex please provide QA notes and description of the ticket
