### ISSUE TITLE
.env.development.local and .env.production.local files are not present in the generated app

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Amplicode/amplicode-frontend#83]

**Comment by owlet1997** [comment]
generator version [0.9.0-next.0](https://www.npmjs.com/package/@amplicode/codegen/v/0.9.0-next.0)

**AR:**
.env.production.local is presented only
![image](https://user-images.githubusercontent.com/45730069/155147178-d6834d84-8d49-4b10-894b-0be21c5dcae2.png)
