### ISSUE TITLE
Drop-down for Association field in Editor screen can't load options

### ISSUE THREAD

**Issue by alexbudarov** [Amplicode/amplicode-frontend#877]
"@amplicode/codegen": "^0.43.0"
Project (for PetClinic) - attached: 
[myclinic7.zip](https://github.com/Amplicode/amplicode-frontend/files/11786371/myclinic7.zip)

- launch
- Open Pet Dto --> Create

Expected: Owner field contains list of entities
Actual: runtime error, because data provider operation that loads list of entities doens't take into account that main "load entities" query may be with paging, and creates invalid GraphQL query.

![image](https://github.com/Amplicode/amplicode-frontend/assets/6158807/e735378b-eef5-458e-8730-c3205ce26c0a)

```
2023-06-19 12:56:21.183  WARN 86031 --- [nio-8080-exec-6] notprivacysafe.graphql.GraphQL           : 
Query did not validate : '{
  ownerList {
    address
    city
    email
    firstName
    id
    lastName
    telephone
    __typename
  }
}'

```

Schema:
```
type Query {
  ownerList(filter: OwnerFilterInput, page: OffsetPageInput, sort: [OwnerOrderByInput]): OwnerDTOResultPage

```

### QA Notes
Fix version - 0.46.x

**Comment by MaslovMaximV** [comment]
**IDEA version**: IntelliJ IDEA 2023.1.3 (Ultimate Edition)
**OS**: macOS 13.3.1
**Plugin version**:
    com.intellij.lang.jsgraphql (4.0.1)
    com.haulmont.amplicode (0.1.SNAPSHOT2928-231)
**Generator version**: 0.46.0

Steps:
1. Open petclinic
2. Use the frontend from the myclinic project.
3. Backend and frontend has been started.

AR: The problem with the Owner field persists.

Query:
![Image](https://github.com/Amplicode/amplicode-frontend/assets/126795807/27454cd9-bd65-4a6d-a315-df68f8e44c31)

![Image](https://github.com/Amplicode/amplicode-frontend/assets/126795807/3838b2b9-feb6-430b-8174-452f07d0f6e2)

**Comment by alexbudarov** [comment]
The problem still persists in "^0.51.0"

**Comment by alexbudarov** [comment]
I created another ticket with a reproduction project.
