### ISSUE TITLE
Generating non-compilable layout.

### ISSUE THREAD

**Issue by MaslovMaximV** [Amplicode/amplicode-frontend#888]
**Plugin version**: IntelliJ IDEA 2023.1.3 (Ultimate Edition)

**OS**: macOS 13.3.1

**Plugin version**:

    com.intellij.lang.jsgraphql (4.0.1)

    com.haulmont.amplicode (0.1.SNAPSHOT2900-231)

**Steps**:

Add the code to the component:
```typeScript
const [data, setData] = useState([
    {
      id:1,
      name:"Sasha",
      lastName:"Fedorov",
      family: true,
      age:29,
      sun:true,
      wife:true
    }
  ]);
```

     2. Drag Table (DataGrid) from ReactPalette to the jsx component > Next

     3. Set Expandable row to true

     4. Choose Properties to display = name > Next > Finish

     5. Start preview

**AR**: Compilable code is added to the jsx component, and upon starting the preview, the specified properties are displayed in a tabular format.
**ER**: Non-compilable code is added to the jsx component.

![1](https://github.com/Amplicode/amplicode-frontend/assets/126795807/8d79bfea-8706-481d-8efb-d2642b8fb8fc)
![2](https://github.com/Amplicode/amplicode-frontend/assets/126795807/6cccd5f9-6ea0-4d64-89e8-e59431c9240c)

**Comment by web-devel** [comment]
Fixed in IntelliJ (a user now should specify at least one prop for expand check)
