### ISSUE TITLE
Sorting in the table (DataGrid).

### ISSUE THREAD

**Issue by MaslovMaximV** [Amplicode/amplicode-frontend#889]
**IDEA version**: IntelliJ IDEA 2023.1.3 (Ultimate Edition)

**OS**: macOS 13.3.1

**Plugin version**:

    com.intellij.lang.jsgraphql (4.0.1)

    com.haulmont.amplicode (0.1.SNAPSHOT2900-231)

**Steps**:

1. Add the code to the component:
2. Drag Table (DataGrid) from ReactPalette to the jsx component > Next
3. Set Sort by = name > Next > Finish
4. Start preview.

**AR**: When starting the preview on the screen, the sorting button is not visible and will only appear once we click on a value.
**ER**: The sorting button is visible next to the value.
![Screenshot 2023-06-23 at 15 25 59](https://github.com/Amplicode/amplicode-frontend/assets/126795807/ae5add71-514a-4b85-bb53-b80984867ea2)
P.S.
The sorting was applied to all the values instead of just the one that was selected.
![Screenshot 2023-06-23 at 13 43 52](https://github.com/Amplicode/amplicode-frontend/assets/126795807/740e3a25-d0d6-43c2-ab08-ac2459c2a9e9)

**Comment by MaslovMaximV** [comment]
If you click on the column header, you can invoke the sorting function even if you haven't explicitly set this option.

**Comment by web-devel** [comment]
We won't fix this because:
1. In most cases there will be several **sortable** columns, but we don't know what is default
2. We don't know default order

Anyway it's something that can be tuned after the template is used
