### ISSUE TITLE
When you activate/deactivate the checkbox, buttons pop up above it.

### ISSUE THREAD

**Issue by MaslovMaximV** [Amplicode/amplicode-frontend#894]
**IDEA version**: IntelliJ IDEA 2023.1.3 (Ultimate Edition)
**OS**: macOS 13.3.1
**Plugin version**:
    com.intellij.lang.jsgraphql (4.0.1)
    com.haulmont.amplicode (0.1.SNAPSHOT2910-231)

**Steps:** 
1. Frontend screen has been created
2. Activate/deactivate the checkbox

AR: When you activate/deactivate the checkbox, buttons pop up above it.

https://github.com/Amplicode/amplicode-frontend/assets/126795807/f5d60be9-3bde-44f9-b81e-5b8f3e6fad3a

**Comment by vadimbasko** [comment]
@MaslovMaximV checkboxes are not shown in v0.46, please re-check.

**Comment by MaslovMaximV** [comment]
@vadimbasko Yes, there are no checkboxes in the CardList template currently, but they remain in the DataGrid where this issue persists.

**Comment by web-devel** [comment]
This panel is displayed on top of the `Datagrid` by react admin. In a real world app (not in the preview) it looks ok.
In order to see the panel in the preview, add some padding around the `Datagrid` , e.g.:

```
    <div style={{padding: "64px"}}> //<------- padding
      <ListContextProvider value={listContext}>
        <Paper>
          <Datagrid size="medium"

```
