### ISSUE TITLE
The cards are cropped at the bottom when adding them through the CardList (Grid) Template.

### ISSUE THREAD

**Issue by MaslovMaximV** [Amplicode/amplicode-frontend#905]
**IDEA Version**: IntelliJ IDEA 2023.1.3 (Ultimate Edition)
**OS**: macOS 13.3.1
**Plugin Version**:
    com.intellij.lang.jsgraphql (4.0.1)
    com.haulmont.amplicode (0.1.SNAPSHOT2928-231)
**Steps**:
1. Create a CardList (Grid) Template using ReactBuddy in the component's code.
2. Launch a preview of this component.

AR: The cards are displayed cropped at the bottom.

![Screenshot 2023-07-04 at 10 03 57](https://github.com/Amplicode/amplicode-frontend/assets/126795807/e65cea82-f02b-42b5-ba24-9f57d9972b50)
![Screenshot 2023-07-04 at 10 04 11](https://github.com/Amplicode/amplicode-frontend/assets/126795807/12b6ed37-79c6-4278-a769-9892963f5c74)

**Comment by web-devel** [comment]
In the real-world screen it looks ok.
In preview you can add some padding around the `Grid`:

```
    <div style={{padding: "12px"}}> //<----- padding
      <ListContextProvider value={listContext}>
        <Grid container spacing="12">
```
